namespace GenICamCameraCapture.GenTL;

/// <summary>
/// GenTL 1.5 标准错误码
/// </summary>
public enum GC_ERROR : int
{
    GC_ERR_SUCCESS = 0,
    GC_ERR_ERROR = -1001,
    GC_ERR_NOT_INITIALIZED = -1002,
    GC_ERR_NOT_IMPLEMENTED = -1003,
    GC_ERR_RESOURCE_IN_USE = -1004,
    GC_ERR_ACCESS_DENIED = -1005,
    GC_ERR_INVALID_HANDLE = -1006,
    GC_ERR_INVALID_ID = -1007,
    GC_ERR_NO_DATA = -1008,
    GC_ERR_INVALID_PARAMETER = -1009,
    GC_ERR_IO = -1010,
    GC_ERR_TIMEOUT = -1011,
    GC_ERR_ABORT = -1012,
    GC_ERR_INVALID_BUFFER = -1013,
    GC_ERR_NOT_AVAILABLE = -1014,
    GC_ERR_INVALID_ADDRESS = -1015,
    GC_ERR_BUFFER_TOO_SMALL = -1016,
    GC_ERR_INVALID_INDEX = -1017,
    GC_ERR_PARSING_CHUNK_DATA = -1018,
    GC_ERR_INVALID_VALUE = -1019,
    GC_ERR_RESOURCE_EXHAUSTED = -1020,
    GC_ERR_OUT_OF_MEMORY = -1021,
    GC_ERR_BUSY = -1022,
    GC_ERR_AMBIGUOUS = -1023,
}

/// <summary>
/// 设备访问标志
/// </summary>
[Flags]
public enum DEVICE_ACCESS_FLAGS : uint
{
    DEVICE_ACCESS_UNKNOWN = 0,
    DEVICE_ACCESS_NONE = 1,
    DEVICE_ACCESS_READONLY = 2,
    DEVICE_ACCESS_CONTROL = 3,
    DEVICE_ACCESS_EXCLUSIVE = 4,
}

/// <summary>
/// 采集控制标志
/// </summary>
[Flags]
public enum ACQ_START_FLAGS : uint
{
    ACQ_START_FLAGS_DEFAULT = 0,
}

[Flags]
public enum ACQ_STOP_FLAGS : uint
{
    ACQ_STOP_FLAGS_DEFAULT = 0,
    ACQ_STOP_FLAGS_KILL = 1,
}

/// <summary>
/// ACQ_QUEUE_TYPE
/// </summary>
public enum ACQ_QUEUE_TYPE : uint
{
    ACQ_QUEUE_INPUT_TO_OUTPUT = 0,
    ACQ_QUEUE_OUTPUT_DISCARD = 1,
    ACQ_QUEUE_ALL_TO_INPUT = 2,
    ACQ_QUEUE_UNQUEUED_TO_INPUT = 3,
    ACQ_QUEUE_ALL_DISCARD = 4,
}

/// <summary>
/// EVENT_TYPE
/// </summary>
public enum EVENT_TYPE : uint
{
    EVENT_ERROR = 0,
    EVENT_NEW_BUFFER = 1,
    EVENT_FEATURE_INVALIDATE = 2,
    EVENT_FEATURE_CHANGE = 3,
    EVENT_REMOTE_DEVICE = 4,
    EVENT_MODULE = 5,
}

/// <summary>
/// TL INFO 命令枚举
/// </summary>
public enum TL_INFO_CMD : int
{
    TL_INFO_ID = 0,
    TL_INFO_VENDOR = 1,
    TL_INFO_MODEL = 2,
    TL_INFO_VERSION = 3,
    TL_INFO_TLTYPE = 4,
    TL_INFO_NAME = 5,
    TL_INFO_PATHNAME = 6,
    TL_INFO_DISPLAYNAME = 7,
    TL_INFO_GENTL_VER_MAJOR = 8,
    TL_INFO_GENTL_VER_MINOR = 9,
}

public enum INTERFACE_INFO_CMD : int
{
    INTERFACE_INFO_ID = 0,
    INTERFACE_INFO_DISPLAYNAME = 1,
    INTERFACE_INFO_TLTYPE = 2,
}

public enum DEVICE_INFO_CMD : int
{
    DEVICE_INFO_ID = 0,
    DEVICE_INFO_VENDOR = 1,
    DEVICE_INFO_MODEL = 2,
    DEVICE_INFO_TLTYPE = 3,
    DEVICE_INFO_DISPLAYNAME = 4,
    DEVICE_INFO_ACCESS_STATUS = 5,
    DEVICE_INFO_USER_DEFINED_NAME = 6,
    DEVICE_INFO_SERIAL_NUMBER = 7,
    DEVICE_INFO_TIMESTAMP_FREQUENCY = 8,
}

public enum STREAM_INFO_CMD : int
{
    STREAM_INFO_ID = 0,
    STREAM_INFO_NUM_DELIVERED = 1,
    STREAM_INFO_NUM_UNDERRUN = 2,
    STREAM_INFO_NUM_ANNOUNCED = 3,
    STREAM_INFO_NUM_QUEUED = 4,
    STREAM_INFO_NUM_AWAIT_DELIVERY = 5,
    STREAM_INFO_NUM_STARTED = 6,
    STREAM_INFO_PAYLOAD_SIZE = 7,
    STREAM_INFO_IS_GRABBING = 8,
    STREAM_INFO_DEFINES_PAYLOADSIZE = 9,
    STREAM_INFO_TLTYPE = 10,
    STREAM_INFO_NUM_CHUNKS_MAX = 11,
    STREAM_INFO_BUF_ANNOUNCE_MIN = 12,
    STREAM_INFO_BUF_ALIGNMENT = 13,
}

public enum BUFFER_INFO_CMD : int
{
    BUFFER_INFO_BASE = 0,
    BUFFER_INFO_SIZE = 1,
    BUFFER_INFO_USER_PTR = 2,
    BUFFER_INFO_TIMESTAMP = 3,
    BUFFER_INFO_NEW_DATA = 4,
    BUFFER_INFO_IS_QUEUED = 5,
    BUFFER_INFO_IS_ACQUIRING = 6,
    BUFFER_INFO_IS_INCOMPLETE = 7,
    BUFFER_INFO_TLTYPE = 8,
    BUFFER_INFO_SIZE_FILLED = 9,
    BUFFER_INFO_WIDTH = 10,
    BUFFER_INFO_HEIGHT = 11,
    BUFFER_INFO_XOFFSET = 12,
    BUFFER_INFO_YOFFSET = 13,
    BUFFER_INFO_XPADDING = 14,
    BUFFER_INFO_YPADDING = 15,
    BUFFER_INFO_FRAMEID = 16,
    BUFFER_INFO_IMAGEPRESENT = 17,
    BUFFER_INFO_IMAGEOFFSET = 18,
    BUFFER_INFO_PAYLOADTYPE = 19,
    BUFFER_INFO_PIXELFORMAT = 20,
    BUFFER_INFO_PIXELFORMAT_NAMESPACE = 21,
    BUFFER_INFO_DELIVERED_IMAGEHEIGHT = 22,
    BUFFER_INFO_DELIVERED_CHUNKPAYLOADSIZE = 23,
    BUFFER_INFO_CHUNKLAYOUTID = 24,
    BUFFER_INFO_FILENAME = 25,
    BUFFER_INFO_PIXEL_ENDIANNESS = 26,
    BUFFER_INFO_DATA_SIZE = 27,
    BUFFER_INFO_TIMESTAMP_NS = 28,
    BUFFER_INFO_DATA_LARGER_THAN_BUFFER = 29,
    BUFFER_INFO_CONTAINS_CHUNKDATA = 30,
}

public enum INFO_DATATYPE : int
{
    INFO_DATATYPE_UNKNOWN = 0,
    INFO_DATATYPE_STRING = 1,
    INFO_DATATYPE_STRINGLIST = 2,
    INFO_DATATYPE_INT16 = 3,
    INFO_DATATYPE_UINT16 = 4,
    INFO_DATATYPE_INT32 = 5,
    INFO_DATATYPE_UINT32 = 6,
    INFO_DATATYPE_INT64 = 7,
    INFO_DATATYPE_UINT64 = 8,
    INFO_DATATYPE_FLOAT64 = 9,
    INFO_DATATYPE_PTR = 10,
    INFO_DATATYPE_BOOL8 = 11,
    INFO_DATATYPE_SIZET = 12,
    INFO_DATATYPE_BUFFER = 13,
    INFO_DATATYPE_PTRDIFF = 14,
}

public enum PORT_INFO_CMD : int
{
    PORT_INFO_ID = 0,
    PORT_INFO_VENDOR = 1,
    PORT_INFO_MODEL = 2,
    PORT_INFO_TLTYPE = 3,
    PORT_INFO_MODULE = 4,
    PORT_INFO_LITTLE_ENDIAN = 5,
    PORT_INFO_BIG_ENDIAN = 6,
    PORT_INFO_ACCESS_READ = 7,
    PORT_INFO_ACCESS_WRITE = 8,
    PORT_INFO_ACCESS_NA = 9,
    PORT_INFO_ACCESS_NI = 10,
    PORT_INFO_VERSION = 11,
    PORT_INFO_PORTNAME = 12,
}

public enum URL_INFO_CMD : int
{
    URL_INFO_URL = 0,
    URL_INFO_SCHEMA_VER_MAJOR = 1,
    URL_INFO_SCHEMA_VER_MINOR = 2,
    URL_INFO_FILE_VER_MAJOR = 3,
    URL_INFO_FILE_VER_MINOR = 4,
    URL_INFO_FILE_VER_SUBMINOR = 5,
    URL_INFO_FILE_SHA1_HASH = 6,
    URL_INFO_FILE_REGISTER_ADDRESS = 7,
    URL_INFO_FILE_SIZE = 8,
    URL_INFO_SCHEME = 9,
    URL_INFO_FILENAME = 10,
}
